version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: user-system-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - user-system-network

  redis:
    image: redis:7-alpine
    container_name: user-system-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - user-system-network

  backend:
    build:
      context: ./backend
      target: development
    container_name: user-system-backend
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/userdb?schema=public
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - user-system-network
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: user-system-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - user-system-network

volumes:
  postgres_data:
  redis_data:

networks:
  user-system-network:
    driver: bridge 